
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

mp.jwt.verify.issuer=airhacks
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApe7ABdcNQE7IJ8ZA5lYNqhobcJWymMA9JcyoqJGJljUnDxtT5L3wnmZIHDq5zFMCG4q5rTtyuc7MpHEli4p529EPJnVkIK1GKiOW7DMyDCSaSaiE8n6+o0NEXWnLBB1d+pLr2V9ExRYLdH6L/77TM9aYhp03+VojUYxW99EkWU8WHOJyni5kx1B/J2peGZaVm50yU1nsQLFS5RY2vq4NwJv5m/TbnJdWa7obl8hKDzhTsTn9S7v/1ShgO1zKmDOtl58NVS5o7h+eMq++jqgqMhHPR8Fx4xsmQjoflhA1fkjFMrl0D9lpUNBJ+p0173j8K2bYOXWtvRKNmcA505KdKwIDAQAB
