#!/bin/sh
mvn clean package
docker build -t test/MovieApplication .
docker rm -f MovieApplication 2>/dev/null || true
docker run -it --name MovieApplication -p 8080:8080 --name MovieApplication test/MovieApplication
